spring.application.name=inventory-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/supply_chain_db
spring.datasource.username=root
spring.datasource.password=Canara@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true